- hosts: localhost
  become: true
  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/config_fish.yml
    - include: tasks/copy_assets.yml
    - include: tasks/config_kvantum.yml
